# Generated by Django 5.2.4 on 2025-07-10 14:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=tinymce.models.HTMLField(verbose_name='Короткое описание'),
        ),
    ]
