# Generated by Django 5.2.4 on 2025-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
